# Script to hold dict of EFT parameters

HEL_parameters = [
  {'param':'cH','title':'cH', 'value':0.1}, 
  {'param':'cT','title':'cT', 'value':0.1}, 
  {'param':'c6','title':'c6', 'value':0.1}, 
  {'param':'cu','title':'cu', 'value':0.1}, 
  {'param':'cd','title':'cd', 'value':0.1}, 
  {'param':'cl','title':'cl', 'value':0.1}, 
  {'param':'cWW','title':'cWW', 'value':0.1}, 
  {'param':'cB','title':'cB', 'value':0.1}, 
  {'param':'cHW','title':'cHW', 'value':0.1}, 
  {'param':'cHB','title':'cHB', 'value':0.1}, 
  {'param':'cA','title':'cA\'', 'value':0.1, 'divide_by':157.913670416}, 
  {'param':'cG','title':'cG\'', 'value':0.1, 'divide_by':157.913670416}, 
  {'param':'cHQ','title':'cHQ', 'value':0.1}, 
  {'param':'cpHQ','title':'cpHQ', 'value':0.1}, 
  {'param':'cHu','title':'cHu', 'value':0.1}, 
  {'param':'cHd','title':'cHd', 'value':0.1}, 
  {'param':'cHud','title':'cHud', 'value':0.1}, 
  {'param':'cHL','title':'cHL', 'value':0.1}, 
  {'param':'cpHL','title':'cpHL', 'value':0.1}, 
  {'param':'cHe','title':'cHe', 'value':0.1}, 
  {'param':'cuB','title':'cuB', 'value':0.1},
  {'param':'cuW','title':'cuW', 'value':0.1},
  {'param':'cuG','title':'cuG', 'value':0.1}, 
  {'param':'cdB','title':'cdB', 'value':0.1}, 
  {'param':'cdW','title':'cdW', 'value':0.1}, 
  {'param':'cdG','title':'cdG', 'value':0.1}, 
  {'param':'clB','title':'clB', 'value':0.1}, 
  {'param':'clW','title':'clW', 'value':0.1}, 
  {'param':'c3W','title':'c3W', 'value':0.1}, 
  {'param':'c3G','title':'c3G', 'value':0.1}, 
  {'param':'c2W','title':'c2W', 'value':0.1}, 
  {'param':'c2B','title':'c2B', 'value':0.1},
  {'param':'c2G','title':'c2G', 'value':0.1}, 
  {'param':'tcHW','title':'tcHW', 'value':0.1}, 
  {'param':'tcHB','title':'tcHB', 'value':0.1}, 
  {'param':'tcG','title':'tcG\'', 'value':0.1, 'divide_by':157.913670416}, 
  {'param':'tcA','title':'tcA\'', 'value':0.1, 'divide_by':157.913670416}, 
  {'param':'tc3W','title':'tc3W', 'value':0.1}, 
  {'param':'tc3G','title':'tc3G', 'value':0.1}
]
